export type RootStackParamList = {
  Intro: undefined;
  SignIn: undefined;
  SignUp: undefined;
  Dashboard: undefined;
  Calender: undefined;
  AddTask: undefined;
  EditTask: {taskId: string; taskType: 'daily' | 'priority'};
  DailyTaskDetails: {taskId: string};
  PriorityTaskDetails: undefined;
  ForgotPassword: undefined;
  ResetPassword: undefined;
  AccountCreated: undefined;
  AddedTask: undefined;
  EditedTask: undefined;
  LoggedOut: undefined;
  TaskDeleted: undefined;
  UpdatedPassword: undefined;
  VerifiedEmail: undefined;
  MainScreen: undefined;
};
